---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBitConfig
metadata:
  name: argo-logs
  namespace: fluent
spec:
  service:
    flushSeconds: 1
    logLevel: info
  outputSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
