---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBitConfig
metadata:
  name: argo-logs
  namespace: fluent
  labels:
    fluentbit.fluent.io/enabled: "true"
spec:
  service:
    flushSeconds: 1
    logLevel: info
