apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
spec:
  destination:
    namespace: workflow-playground
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-events
    repoURL: https://github.com/containerly/platform
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
