apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-operator
  namespace: argocd
spec:
  destination:
    namespace: fluent-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: fluent-operator
    repoURL: https://github.com/containerly/platform
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
