apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch-operator
  namespace: argocd
spec:
  project: default
  source:
    path: opensearch-operator
    repoURL: https://github.com/containerly/platform
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: opensearch-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
