apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/external-secrets/external-secrets/releases/download/v1.2.1/external-secrets.yaml
  - resources/basic-external-secret.yaml
  - resources/basic-secret-store.yaml
