apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - applications/external-secrets-crds.yaml
  - applications/external-secrets-helm.yaml
  - applications/external-secrets-crs.yaml
