apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - https://github.com/fluent/fluent-operator//manifests/setup?ref=v3.5.0
  - resources/opensearch-secret.yaml
  - resources/clusterinput-argo-logs.yaml
  - resources/clusterfilter-argo-logs.yaml
  - resources/clusteroutput-opensearch.yaml
  - resources/clusterfluentbitconfig-argo-logs.yaml
  - resources/clusterfluentbit-argo-logs.yaml
