apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/VictoriaMetrics/operator/config/default?ref=v0.65.0
# Uncomment and set these if you want to override the image or namespace for VictoriaMetrics Operator
images:
  - name: manager
    newName: victoriametrics/operator
    newTag: ${VM_VERSION}
