apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - event-sources/github.yaml
  - eventbus/native.yaml
  - sensors/github.yaml
  - rbac/sensor-rbac.yaml
  - rbac/workflow-rbac.yaml
