apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argo-events/event-sources/github.yaml
  - argo-events/eventbus/native.yaml
  - argo-events/sensors/github.yaml
  - argo-events/rbac/sensor-rbac.yaml
  - argo-events/rbac/workflow-rbac.yaml
