apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/argo-cd.yaml
  - base/argo-events.yaml
  - base/argo-rollouts.yaml
  - base/argo-workflows.yaml
  - base/argocd-image-updater.yaml
  - base/external-secrets-operator.yaml
  - base/cluster-config.yaml
  - base/cert-manager.yaml
  - base/grafana-operator.yaml
  - base/prometheus-operator.yaml
  - base/fluent-operator.yaml
  - base/strimzi-cluster-operator.yaml
  - base/sealed-secrets.yaml
