---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-dashboard.yaml
  - grafana-datasource.yaml
  - grafana.yaml
  - kafka-nodepool.yaml
  - kafka.yaml
  - flux-instance.yaml
  - opensearch-cluster.yaml
  - vmsingle.yaml
