---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strimzi-system
resources:
  - resources/namespace.yaml
  - https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.49.1/strimzi-cluster-operator-0.49.1.yaml
  - resources/kafka-cluster.yaml
  - resources/kafka-nodepool.yaml


