---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.49.1/strimzi-cluster-operator-0.49.1.yaml
  - resources/kafka-cluster.yaml
  - resources/kafka-nodepool.yaml
  - resources/kafka-connect.yaml
  - resources/kafka-topic-argo-logs.yaml
  - resources/kafka-connector-argo-logs.yaml
  - resources/rbac-lease-access.yaml
  - resources/rbac-operator-watch.yaml
