---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/operators/grafana-operator
  - ../../../base/operators/opensearch-operator
  - ../../../base/operators/victoriametrics-operator
