---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opensearch-system
resources:
  - namespace/namespace.yaml

helmCharts:
  - name: opensearch-operator
    repo: https://opensearch-project.github.io/opensearch-k8s-operator/
    releaseName: opensearch-operator
    namespace: opensearch-system
    includeCRDs: true
