apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
helmCharts:
  - name: opensearch-operator
    repo: https://opensearch-project.github.io/helm-charts/
    version: 2.12.0
    releaseName: opensearch-operator
    includeCRDs: true
    valuesInline:
      serviceAccount:
        create: true

resources:
  - resources/opensearch-operator.yaml
