---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: victoria-metrics-system
resources:
  - resources/namespace.yaml
  - https://github.com/VictoriaMetrics/operator/releases/download/v0.66.1/install-with-webhook.yaml


