---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-operator-application.yaml
  - strimzi-kafka-operator-application.yaml
  - victoriametrics-operator-application.yaml
