apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoriametrics-operator
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: victoria-metrics-operator
  source:
    repoURL: https://github.com/VictoriaMetrics/operator.git
    targetRevision: HEAD
    path: config/default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
